- hosts: localhost
  gather_facts: false
  tasks:
  - name: Create In-memory Inventory
    add_host: 
      name: workstation-{{osp_GUID}}.rhpds.opentlc.com
      group: workstation
 
- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
      cloud: ospcloud
      server: 'frontend'
    register: openstack_info

  - name: Curl website
    uri:
       url: "http://{{item.public_v4}}"
       return_content: yes
    with_items:
       - "{{ openstack_info.ansible_facts.openstack_servers }}"
    register: webpage
  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
       msg: "Three Tier App deployment on QA failed"
    when: "'Ansible has done its job' not in webpage.results[0].content"
